### ISSUE TITLE
Modify boojum based aggregator to support different proving algorithms

### ISSUE THREAD

**Issue by PossiblyHarry** [EYBlockchain/zk-swap-ZoKrates#9]
Currently it only supports PGHR13, will need to support others (such as GM17 and Groth16) as they are more efficient to prove and verify.

Boojum uses the knapsack hash (`CRH_with_field_out_gadget`) to authenticate the verification key and proof inputs.

The `batch` function constructs an instance of the aggregator at:

https://github.com/EYBlockchain/zk-swap-ZoKrates/blob/d6366f150626b2a64b7d823878368ea800c8bf11/zokrates_core/lib/pghr13.cpp#L263

The batch interface only supports a batch of two at a time.

It also generates a new keypair every time, at: https://github.com/EYBlockchain/zk-swap-ZoKrates/blob/d6366f150626b2a64b7d823878368ea800c8bf11/zokrates_core/lib/pghr13.cpp#L265

The `batch` C++ function is handled in rust at: https://github.com/EYBlockchain/zk-swap-ZoKrates/blob/5c681035278f496fef49e592e180507b92733aae/zokrates_core/src/proof_system/batch.rs

## TODO?

 * [ ] Modify aggregator to support multiple proof systems
 * [ ] Modify Groth16 verification gadget to be compatible with aggregator
 * [ ] Implement GM17 verification gadget, compatible with aggregator
 * [ ] Support persistent keypair for aggregator

**Comment by PossiblyHarry** [comment]
Closing as a different method will be used to recursion.
